[project]
name = "speech-aging-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Eryk Urbański", email = "eryk.urbanski14@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.5",
    "ipykernel>=7.3.0",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "polars[pyarrow]>=1.43.2",
    "pyarrow>=25.0.1",
    "scipy>=1.18.0",
]

[project.scripts]
speech-aging-analysis = "speech_aging_analysis:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
